### PR TITLE
Heaps of Updated Texture Names and New Textures

### PR DESCRIPTION
**Pull request by aws404**
Updated texture names for:
Immersive Engineering
Ender Storage
Better Advancements/Achievements
Draconic Evolution
JEI Resources
Roots

New Textures for:
Redstone Aresonal
Immersice Engineering
Thermal Expansion
Not Enough Wands

### CODE REVIEW

**Comment by StefanTT** [comment]
again contains pdn file(s)

**Comment by aws404** [comment]
Done

**Comment by garrim** [comment]
I don't really understand.
Is this a new version? And what version number are you on?
And what are all the files in the TODO folder.

Sorry for asking stupid questions, but I really love tour respak and I'd
love to have the latest, updated versions of it.

Kind regards
Göran

**Comment by StefanTT** [comment]
The TODO folder contains the textures that are not yet done.

**Pull request merged**
