### PR TITLE
Work Stuff

### PR DESCRIPTION
**Pull request by anders0nmat**
Uhh, look Commits for further Informations.
Sorry for Conflict, dont know how to fix it, weird Stuff is happening, also sorry for all those Commits, i will get myself a new fork after this merge

### CODE REVIEW

**Comment by anders0nmat** [comment]
I dont know where exactly i should fix it... i dont have write access so i cant fix it here but how do i fix it otherwise

**Comment by StefanTT** [comment]
You have to fix it in your repository then the pull request is automatically fixed.

**Comment by anders0nmat** [comment]
But in my repository is no conflict...

**Comment by anders0nmat** [comment]
ah, i tipped some comands, clicked some random buttons and somehow it worked

**Pull request merged**
