### PR TITLE
Ethryan greg patch

### PR DESCRIPTION
**Pull request by Ethryan**
The pull for Gregtech Community Edition.
Will try and add as much as i can.

Snip^^
Only missing GUI, and those are in a completely different format.
#90

### CODE REVIEW

**Comment by StefanTT** [comment]
Have a look at the 1.7.10 textures, if you did not already. I did a bunch of Gregtech stuff back then that you could reuse.

**Comment by Ethryan** [comment]
Already doing that, but it's a lot of renaming.

**Comment by StefanTT** [comment]
If it's "TheItem" to  "the_item" then I have a script for renaming.

**Comment by Ethryan** [comment]
That would be useful, I am done with the items for now, but i still have to do the blocks.

**Comment by Ethryan** [comment]
Done for now i think.

Ready for testing.

**Pull request merged**
