### PR TITLE
Update

### PR DESCRIPTION
**Pull request by thewawpro**

### CODE REVIEW

**Comment by anders0nmat** [comment]
Are you sure that there are textures in the plain \assets folder? In particular im talking about "big_smoke_0" to "big_smoke_11" and "soul_fire_flame"

**Comment by thewawpro** [comment]
Sorry I messed up on something just delete them.

**Comment by StefanTT** [comment]
Don't you want to clean up your mess yourself? ^.-

**Comment by thewawpro** [comment]
I would but I am new to github, and I know how to delete from the forked repo but I dont know what to do after that.

**Comment by StefanTT** [comment]
Push it as a change request like if you have added something.

**Comment by StefanTT** [comment]
```
git rm big_smoke_*
git commit -m "Removed bogous files"
git push
```
don't bother, I have done it now.

**Pull request merged**
