### PR TITLE
Some README Fixes

### PR DESCRIPTION
**Pull request by anders0nmat**
Fixed Typos and added Minecraft to Modlist, will try to finish Minecraft in next days

### CODE REVIEW

**Comment by StefanTT** [comment]
It looks like your repository is not very clean. I hesitate to merge this mess as it only contains one changed file.

**Comment by anders0nmat** [comment]
well, i understand you, but i dont know how to fix my repository.

**Comment by anders0nmat** [comment]
well... i really have no clue why there are so many commits and i really wanna find out. It annoys me to see walls of commits that dont effect the master branch and i cant do anything about it, so if someone know why this happens please tell me.

**Comment by Intipablo** [comment]
I'm having this issue aswell @anders0nmat . I think what I'm going to do is just delete my fork and create a new fresh one.

**Comment by anders0nmat** [comment]
I dont know if im right but 'syncing forks' sounds like the solution but this requires Git and i already have problems with understanding and using the much easier GitHub.
I think i will do so too, but this problem will appear again in a few commits. Is it really the solution to do some commits, delete the Fork and get another Fork just to do some commits and delete the fork again?

**Comment by Intipablo** [comment]
I'm really not sure. I might have to look into Git more and try to figure out how to use it.

I thought my internet was bad (Australia), but several hours is a long time...

**Comment by anders0nmat** [comment]
can you keep me up to date? bc we really need a better solution and i have no time right now to read and understand those git guides.

**Pull request merged**
