### PR TITLE
TE Machine Interface + JEI

### PR DESCRIPTION
**Pull request by anders0nmat**
(Hopefully) Fixed JEI fuckup for Thermal Expansion + did some Copy & Paste for GUI of Glacial Precipitatorator (The Snowball Machine)

### CODE REVIEW

**Comment by mcdodge34** [comment]
FYI the Igneous Extruder also changed with a block output selection like in the Glacial Precipitator instead of its previous GUI.

**Comment by anders0nmat** [comment]
yeah, i will focus on TE for now... but it's very hard work (first time for me to do this stuff)

**Comment by mcdodge34** [comment]
Good to see, all efforts are always appreciated, can you also take a look at the ores and ingots, there's a few new ones like Constantan, Aluminum and Iridium from TE that are still showing with default textures.

**Comment by anders0nmat** [comment]
i will try my best but multi colored textures with color gradient are my weakness. im currently working on TF coins but im in despair. (im sorry for bad english, im pretty shitty at writing...)

**Pull request merged**
