### PR TITLE
Deleted Minecraft, worked on TE and COFH

### PR DESCRIPTION
**Pull request by anders0nmat**
Added COFH GUIs
Added TE Augments (some of them)

Deleted Minecraft textures, see xMrVizzy for a more complete version of vanilla textures

### CODE REVIEW

**Comment by StefanTT** [comment]
Quite a bold move :-1:

**Comment by Intipablo** [comment]
This decision was something me and anders0nmat discussed on Discord and with others on reddit. We decided that updating vanilla textures wasn't a priority (we are missing alot) and since we are now on CurseForge and that's where most people will get the pack from now on, there is a much better, more updated vanilla pack over at xMrVizzy's Faithful Java that could be used alongside ours.

However we never talked to you about any of this, and for that I have to apologize. Please tell us if you have any problems with the decision.

**Comment by StefanTT** [comment]
Then please update the website of f32.me and the main README of the repository to inform those that do not use Curse.

It's disturbing that something like this is not discussed on Github in the issues, where it belongs, instead of somewhere else. I can remember some discussions about merging repositories with xMrVizzy's. Seems that this was decided to be no option.

But hey you two are more active than me in the last couple of months, so it's probably not me any longer who needs to care. Go along, but update f32.me and the README.md.

**Comment by Intipablo** [comment]
Yeah it was our fault, I often forget about discussion on GitHub as I am on Discord talking all the time. So my bad. We are currently in the process of getting FTP access to F32.me from greenphelm, after that we can update it. I'll get anders0nmat to update the GitHub README too. :+1: 

Yes I attempted a merge with xMrVizzy but he never responded, so we went ahead on our own.

**Comment by StefanTT** [comment]
I remember reading in one of the issue discussions that he is currently very busy.

**Pull request merged**
