### PR TITLE
DE, EE and WCT

### PR DESCRIPTION
**Pull request by anders0nmat**
Added Draconic Evolution textures
Added WCT textures
Added some more Skyresources Textures
Added Equivalent Energistics textures

@StefanTT i reworked the Draconic Evolution items (like the ingots and nuggets) you can decide whether they will be used or your textures of them

EDIT: oh seems like they just disappeared somewhere in this spaghetti of commits of mine

### CODE REVIEW

**Comment by Ethryan** [comment]
I think the Draconium Dust looks a little flat, otherwise everything looks nice. 
Good job.

**Comment by StefanTT** [comment]
We already have at least the draconic dust in a not so flat version. Not?

**Comment by anders0nmat** [comment]
ok then. i deleted it in my branch

**Comment by StefanTT** [comment]
Sorry to come back quite late, I noticed that the dragon heart icon is very nice but very obviously a different icon than the original.

**Comment by anders0nmat** [comment]
Yeah, i just copied the old texture.

**Comment by anders0nmat** [comment]
if this is a problem, i can edit the heart texture. i would take the old texture and add a colored background and apply some noise-like effects additionally to a additive merge.

**Comment by StefanTT** [comment]
Yeah something that looks more like the original 16x16 heart would be great.

**Comment by anders0nmat** [comment]
I am very busy right now so i cant do it right away. If someone has an idea to improve the said texture you are welcome. I can work on it earliest in like 1-2 months

**Comment by StefanTT** [comment]
No problem, I will make it when I find time. Or anybody else. It is not that big of an issue :-)

**Comment by anders0nmat** [comment]
thank you. tbh i am currently not very interested in making textures besides some important work i have to do. But thats the advantage of open-source projects i guess. Thanks again :-)

**Pull request merged**
