### PR TITLE
SkyOrchards, Better Advancements, Tinkers' Construct & Tinkers' Complement

### PR DESCRIPTION
**Pull request by Bernasss12**
Fully textured Sky Orchards v0.0.12
Fully textured Better Advancements v0.1.0.77
Partially updated Tinkers' Construct v2.12.0.135

### CODE REVIEW

**Comment by StefanTT** [comment]
Tell me when you are finished.

**Comment by Bernasss12** [comment]
Sure, maybe another days's work will suffice, I hope!

**Comment by Bernasss12** [comment]
All done, took a lot longer than I expected but my free time was cut short

**Comment by StefanTT** [comment]
Still working on it?

I think it would be better to merge stuff every couple of days. If you create a pull request it is usually expected that the stuff is in a shape where _you_ feel that it is ready for being merged. Using pull requests as work info is not the best way of doing things IMO. No offense :-)

**Comment by Bernasss12** [comment]
Yes it's been done for a while now, I'm just always working on adding more stuff and have been pushing while the pull request is open.
The thing is I don't really know how every works in GitHub with forks and merges, am I supposed to close the pull request before it being accepted?

**Comment by StefanTT** [comment]
You create the pull request when you are done with the work.
When I (or whoever) merges it then the pull request gets automatically closed.
When there are things to fix then the pull request stays open like this one and you can add more stuff to it.

**Pull request merged**
