### PR TITLE
Even More Texture Fixes

### PR DESCRIPTION
**Pull request by agarian-2**
**Fixes:** Quicksand, most of the remaining planks, most remaining logs, ALL leaves.

**EDIT:** Not sure why it shows the previous changes I made in my last PR, I guess I should delete my fork and refork this when this gets merged.

**EDIT 2:** Done making changes.

### CODE REVIEW

**Comment by Bernasss12** [comment]
You can

**Comment by Bernasss12** [comment]
After the pr was merged you either have to restart your local repo or fetch the changes from origin

**Comment by agarian-2** [comment]
M'kay, I'll take note of that next time.

**Comment by Bernasss12** [comment]
Sure, if you need any help you can ask here or over on the Discord

**Comment by agarian-2** [comment]
<s>And by that I'll procrastinate it and do it the hard way</s>

**Comment by agarian-2** [comment]
Funny thing about a lot of these textures is all I have to do is change the color balance of the image and sometimes flip textures around. Anyways, all done for now; this may be merged now.

**Pull request merged**
