### PR TITLE
Updated Mod List, Added 1.7 Textures

### PR DESCRIPTION
**Pull request by anders0nmat**
Updated Mod list
Added AkashicTome Texture
Added 1.7 textures for mods on Mod List

### CODE REVIEW

**Comment by StefanTT** [comment]
Conflicting files.

**Comment by StefanTT** [comment]
@anders0nmat please fix the conflict it cannot be merged.

**Comment by anders0nmat** [comment]
well... i changed some stuff, how can i fix the conflict if its part of my work?

**Comment by StefanTT** [comment]
I think the internet has some Github tutorials, please have a look there.
I fixed the conflicting file, hopefully this is the version you intended.

**Pull request merged**
